version: '3'
services:

  web:
    image: nginx:1.23-alpine
    container_name: web
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    links:
      - php
    volumes:
      # html 目录
      - ./html/:/var/www/html
      # Nginx 配置
      # - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      # Nginx 站点配置
      - ./conf.d/:/etc/nginx/conf.d/
      # SSL 证书
      - ./ssl/www:/var/www/certbot/:ro
      - ./ssl/conf/:/etc/nginx/ssl/:ro

  ssl:
    image: certbot/certbot
    container_name: ssl
    restart: always
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - web
    volumes:
      - ./ssl/www/:/var/www/certbot/:rw
      - ./ssl/conf/:/etc/letsencrypt/:rw
    # Automatic Certificate Renewal
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  php:
    image: joseluisq/php-fpm:8.1
    container_name: php
    restart: always
    environment:
      - TZ=Asia/Shanghai
      # https://github.com/joseluisq/alpine-php-fpm
      - ENV_SUBSTITUTION_ENABLE=true
      # /usr/local/etc/php-fpm.conf
      # - phpFPM_ERROR_LOG=/proc/self/fd/2
      # - phpFPM_LOG_LEVEL=error
      # /usr/local/etc/php-fpm.d/www.conf
      - phpFPM_LISTEN=9000
      # - phpFPM_USER=www-data
      # - phpFPM_GROUP=www-data
      # - phpFPM_LISTEN_OWNER=www-data
      # - phpFPM_LISTEN_GROUP=www-data
      # /usr/local/etc/php/conf.d/default-php.ini file (php.ini).
      - phpEXPOSE_PHP=On
      - phpMEMORY_LIMIT=512M
      - phpSESSION_GC_MAXLIFETIME=7200
    expose:
      - 9000
    ports:
      - '172.17.0.1:9000:9000'
    volumes:
      # 程序路径
      - ./html:/var/www/html
      # 通过替换配置 禁用某些拓展
      # - ./php/conf.d/docker-php-ext-swoole.ini:/usr/local/etc/php/conf.d/docker-php-ext-swoole.ini
      # 通过环境变量进行设置
      # - ./php/conf.d/default-php.ini:/usr/local/etc/php/conf.d/default-php.ini
      # 替换整个配置文件夹 提前 cp conf.d
      # - ./php/conf.d/:/usr/local/etc/php/conf.d/

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root@123
    expose:
      - 3306
    ports:
      - '172.17.0.1:3306:3306'
    volumes:
      - ./mariadb:/var/lib/mysql

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root@123
    expose:
      - 5432
    ports:
      - '172.17.0.1:5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
      
  redis:
    image: redis:3-alpine
    container_name: redis
    restart: always
    environment:
      - TZ=Asia/Shanghai
    expose:
      - 6379
    ports:
      - '172.17.0.1:6379:6379'
      
  memcached:
    image: memcached:alpine
    container_name: memcached
    restart: always
    environment:
      - TZ=Asia/Shanghai
    expose:
      - 11211
    ports:
      - '172.17.0.1:11211:11211'
      