version: '3.3'
services:
  postgres:
    image: postgres:alpine
    network_mode: hosting_running_network
    restart: always
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1530519209
    container_name: db_postgres
    # postgresql://username:password@host:port/dbname[?paramspec]
